apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~2.8
spec:
  releaseName: fluent-bit
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: fluent-bit
    version: 2.8.5
#   values:
#     image:
#       tag: 1.3.5
