---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo-api
  namespace: amitt
  annotations:
    fluxcd.io/automated: "true"
    #flux.weave.works/automated: "true"
    #fluxcd.io/tag.chart-image: semver:~2.8
spec:
  releaseName: demo-api
  chart:
    repository: http://192.168.1.79:8080
    name: demo-api
    version: 1.1.9
  values:
    image:
      repository: amithapa/techmang3-api
      tag: 1.16.7
